# testbench
fft_tb.v
sram_model/SRAM_real_480x32b.v
sram_model/SRAM_imag_480x32b.v

# netlist generated by Design Compiler
../syn/netlist/fft_syn.v
# Logic Gate models
-v /theda21_2/library/GPDK045/cur/gsclib045/verilog/slow_vdd1v2_basicCells.v

+define+GATESIM
+access+r
